### ISSUE TITLE
Editor: Dragging and dropping media uploads it but does not add it to the post

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-calypso#23208]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/post
2. Select a site to start a new post.
3. Drag and drop an image into the body of the post.

#### What I expected

I expected the image to be uploaded and added to the post.

#### What happened instead

Nothing visibly happened; no image was added to the post (I checked both Visual and HTML tabs). The console shows this error:

> Uncaught TypeError: e.execCommand is not a function

When I opened the media library, I saw that the image was uploaded and I could add it to the post from there.

#### Browser / OS version

macOS 10.13.3 / Multiple browsers (tried both Chrome and Firefox)

#### Screenshot / Video

Console error:
![screenshot 2018-03-10 20 13 08](https://user-images.githubusercontent.com/8658164/37246396-5339f718-24a0-11e8-9515-1e632a323e29.png)

#### Context / Source
#dogfooding

**Comment by alisterscott** [comment]
I was able to reproduce this, I think this is a regression as I am sure this used to work.

**Comment by alisterscott** [comment]
I think this was caused by #21734

**Comment by nylen** [comment]
Fix available in #23233.

**Comment by folletto** [comment]
![cap-bug-drag-drop](https://user-images.githubusercontent.com/4389/37298314-d8aee08e-2617-11e8-90a5-1716b7a3d5fb.gif)

I came here to report the same, I'll just attach the GIF instead.
