### ISSUE TITLE
Settings: the section does not load

### ISSUE THREAD

**Issue by vindl** [Automattic/wp-calypso#24598]
#### Steps to reproduce
1. Starting at URL: `https://wordpress.com/settings/general/{site}` (happens only for some sites)
2. The page doesn't load (tested in `dev` and `stage`).

It errors out with:
``` 
TypeError: langSlug.split is not a function
    at getLanguageCodeLabels
...
```

It looks like it was introduced in https://github.com/Automattic/wp-calypso/pull/24562.

**Comment by frontdevde** [comment]
Thanks for reporting, @vindl! Taking a look now.

**Comment by frontdevde** [comment]
@vindl 
Can't reproduce the issue at the moment, will try further. Could you let me know whether you're seeing the issue on Simple or Atomic/Jetpack site(s)? Also which language do you have selected on the site(s) on which the error occurs?

**Comment by vindl** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/24602.
