### PR TITLE
Fix adding domain and plan to cart in signup flow

### PR DESCRIPTION
**Pull request by delputnam**
#### Changes proposed in this Pull Request

* Fixing a bug introduced in https://github.com/Automattic/wp-calypso/pull/52355 related to adding products to the signup flow when there is no site selected.
* It looks like `newCartItems` is an object, so `map` won't work there.

This shows how to replicate the error:

#### Testing instructions

Without a specific site selected, go to the /domains/manage page
Select "Add a domain"
Enter some query text
Select a domain
Select "Existing WordPress.com Site"
Select a site
Select a plan
Make sure that you end up on the shopping cart page after a moment
Check the console to make sure there are no errors like "Uncaught TypeError: newCartItems.map is not a function"

### CODE REVIEW

**Comment by sirbrillig** [comment]
😬  Interesting. Nice job tracking this down. I can see that most of the time, the `SignupCart` functions are called with the second argument being an array, for example here:

https://github.com/Automattic/wp-calypso/blob/b6155a8dfa6a249f272fa0a158be162650e39e29/client/lib/signup/step-actions/index.js#L81-L84

But there is one place where one of the functions is called with something that does look like an object (it's hard to tell from the code because of the heavy use of lodash):

https://github.com/Automattic/wp-calypso/blob/b6155a8dfa6a249f272fa0a158be162650e39e29/client/lib/signup/step-actions/index.js#L91-L100

Since I _think_ that's the only place that's not using an array, maybe if we modify that code to pass an array instead of changing the function signature to widen its types will make this code less likely to have similar bugs in the future.

Also (and this can be separate from this PR) it would be nice if we had a test to prove this failure and protect against it in the future.

**Comment by sirbrillig** [comment]
I think replacing [the code mentioned above](https://github.com/Automattic/wp-calypso/blob/b6155a8dfa6a249f272fa0a158be162650e39e29/client/lib/signup/step-actions/index.js#L91-L100) with something like this would fix this without having to touch the cart function:

```js
SignupCart.createCart(
	siteId,
	[ dependencies.domainItem, dependencies.privacyItem, dependencies.cartItem ].filter(
		Boolean
	),
	( error ) => {
		callback( error, providedDependencies );
	}
);
```

**Comment by delputnam** [comment]
Thanks for having a look @sirbrillig!  Your solution does make more sense.  I've tested your proposed code successfully and updated the PR.

**Review by sirbrillig — APPROVED** [review]
This looks good to me! Thanks! 

I'm a _little_ concerned about this e2e test failure:

> [WPCOM] Managing Domains: ... Adding a domain to an existing site

> Can select the .com search result ...

The [failing test](https://github.com/Automattic/wp-calypso/blob/b6155a8dfa6a249f272fa0a158be162650e39e29/test/e2e/specs/specs-calypso/wp-manage-domains-spec.js#L88-L92) seems to be hanging when clicking to select a domain on the domain search page.

However, I just tested it manually on this branch and I can't reproduce, so hopefully it's just a flaky test. 🤞

**Comment by sirbrillig** [comment]
A screenshot of the failing test in case you can reproduce it.

Screen Shot 2021-05-22 at 10 45 04 AM

**Comment by delputnam** [comment]
I wasn't able to reproduce the failing test manually either.

**Comment by sirbrillig** [comment]
:shipit:
