### PR TITLE
Agents Manager: fix Big Sky event name type error

### PR DESCRIPTION
**Pull request by lucatume**
## Proposed Changes

* Fix the TS2345 error in `packages/agents-manager/src/hooks/custom-actions/index.ts` that breaks `type_check_packages` on trunk: tighten `recordGuardedBigSkyTracksEvent`'s runtime guard to check the `jetpack_big_sky_` prefix (matching what its doc comment already claims) and assert the narrowed template-literal type at the call. `startsWith` does not narrow template-literal types, so the assertion is required.

## Why are these changes being made?

* Trunk is currently broken for all PRs: the "Unit tests (Web app)" build fails on `type_check_packages` with:
  ```
  packages/agents-manager/src/hooks/custom-actions/index.ts:26:27 - error TS2345:
  Argument of type 'string' is not assignable to parameter of type '`jetpack_big_sky_${string}`'.
  ```
* Root cause is a semantic merge conflict between two PRs that each passed CI alone: #113786 narrowed `recordBigSkyTracksEvent`'s `eventName` parameter to `` `jetpack_big_sky_${string}` ``, and #113742 added the caller `recordGuardedBigSkyTracksEvent(eventName: string, ...)` passing a plain string.
* TeamCity evidence: build 19164658 (`fbd8a7dbcd3`, parent of the second PR's merge) is green; 19164914 (`c590e1b309f`) and 19165757 (trunk head `1a6c7d37c35`) both fail with the identical error.

## Testing Instructions

* Run `yarn typecheck-packages` on trunk — it fails with the error above.
* Run it on this branch — it passes.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://github.com/Automattic/wp-calypso/blob/trunk/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] For UI changes, have you tested the affected components in [dark mode](https://github.com/Automattic/wp-calypso/blob/trunk/docs/dark-mode.md)?
- [ ] Have you tested accessibility for your changes? Ensure the feature remains usable with various user agents (e.g., browsers), interfaces (e.g., keyboard navigation), and assistive technologies (e.g., screen readers) (PCYsg-S3g-p2).
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

File: packages/agents-manager/src/hooks/__tests__/custom-actions.test.ts [hunk 1]
```diff
@@ -134,9 +135,12 @@ describe( 'useSetupCustomActions', () => {
 		window.__agentsManagerActions?.recordBigSkyTracksEvent?.( 'split_screen_guide_click', {
 			component_type: 'proofread',
 		} );
-		expect( mockRecordBigSkyTracksEvent ).toHaveBeenCalledWith( 'split_screen_guide_click', {
-			component_type: 'proofread',
-		} );
+		expect( mockRecordBigSkyTracksEvent ).toHaveBeenCalledWith(
+			'jetpack_big_sky_split_screen_guide_click',
```
Comment (lucatume) [inline packages/agents-manager/src/hooks/__tests__/custom-actions.test.ts:139]: Using the plain string, and not the constant, to keep a relation with backend that will break if the const is changed only on this side.

File: packages/agents-manager/src/hooks/custom-actions/index.ts [hunk 2]
```diff
@@ -23,7 +23,8 @@ function recordGuardedBigSkyTracksEvent(
 		return;
 	}
 
-	recordBigSkyTracksEvent( eventName, props );
+	// Bridge callers pass the suffix only — see `recordBigSkyTracksEvent` in `global.d.ts`.
+	recordBigSkyTracksEvent( `${ BIG_SKY_EVENT_PREFIX }${ eventName }`, props );
```
Comment (jcheringer) [inline packages/agents-manager/src/hooks/custom-actions/index.ts:27]: I think this is good enough for now to fix the current issue.
I'm wondering whether we should require bridge callers to send the full event name as well.
Or whether we should add a check here before appending the prefix to `eventName`.
But that could be a follow-up, I guess.

Do you have thoughts, @iamchughmayank?

**Review by jcheringer — APPROVED** [review]
Looks good. Left a non-blocking comment for a possible follow-up

File: packages/agents-manager/src/hooks/custom-actions/index.ts (hunk 2 above)
Comment (iamchughmayank) [reply packages/agents-manager/src/hooks/custom-actions/index.ts:27]: Yes, having a follow up to make the bridge callers send the full name is probably the best idea because that's the established pattern elsewhere in the repository now that the callers send full name. having bridge exhibiting an exceptional behaviour may not be maintainable. Unfortunately, the change to the prefix landed shortly before I had synced my branch. else, I would have caught this. 

I will raise a follow up PR to bring consistency. Thanks for flagging this :)

Comment (jcheringer) [reply packages/agents-manager/src/hooks/custom-actions/index.ts:27]: > Unfortunately, the change to the prefix landed shortly before I had synced my branch. else, I would have caught this. 

Yeah, that was 'perfect' timing. 😅 

> I will raise a follow up PR to bring consistency. Thanks for flagging this :)

Thanks a lot!
