### PR TITLE
Simplify or remove several package.json scripts

### PR DESCRIPTION
**Pull request by jsnajdr**
Bunch of simplifications of the npm scripts in `package.json`. Followup to #38190 that fixes plenty of things.

**Eliminate the need for setting NODE_PATH when building or running Calypso**
It was needed only to `require` two specific files (webpack config for webpack dev server and search index for devdocs). Updated the webpack `externals` definition to remove that need.

**Fix the NODE_ARGS argument in the start-build scripts**
`node NODE_ARGS=...` is an error that fails the script invocation:
```
Error: Cannot find module '/Users/jsnajdr/src/wp-desktop/calypso/NODE_ARGS=--max_old_space_size=8192'
```
We want to invoke `node` with `$NODE_ARGS` arguments and supply a default.

Cc @nsakaimbo who introduced the regression in #38576.

**Validate fallback build in a separate `post*` script**
Makes lines in `package.json` shorter 🙂 Cc @sgomes 

**Update path to stats.json file in `whybundled` script**
The (rarely used) `npm run whybundled` didn't have a correct path to `stats.json` (inside `client/` since the monorepo-ization)

**Update clean scripts**
Updates the paths of generated files to remove (`server/` to `client/server/`), uses `run-s` to run all `clean:*` scripts at once.

**Remove the analyze-css NPM script**
Finishes the removal started in #27979.

### CODE REVIEW

**Comment by nsakaimbo** [comment]
> Cc @nsakaimbo who introduced the regression in #38576.

Technically, #38576 did not cause a regression. This initial code change was necessary to address changes to memory constraints for wp-desktop that were introduced by Node 12. This change wasn’t an issue until the conversion of the Calypso client into a lerna package.

Regardless - I think it’s worth calling out the language used here. We shouldn’t encourage a culture of finger-pointing. Not saying this was anyone’s intention, but such phrasing could easily be construed this way. We all work together on the same team. Moving forward, we should all (myself included) be mindful of the language we use when solving these issues as they come up.

**Comment by jsnajdr** [comment]
Hi @nsakaimbo 👋 I apologize for not being careful about the phrasing I used. I wanted to call your attention to the part of the diff where your review would be valuable, not to assign blame to you or anyone else. I agree that would be unproductive and pointless.

I still believe that #38576 introduced a bug into the `start-build-fallback` script that's invoked by the `make dev-server` task in the `wp-desktop` repo. While the old code:
```
node $NODE_ARGS --max_old_space_size=8192 build/bundle.js
```
runs the `build/bundle.js` script and "only" fails to use `max_old_space_size` passed in `NODE_ARGS`, the patched code:
```
node NODE_ARGS=${NODE_ARGS:---max_old_space_size=8192} build/bundle.js
```
fails to run the script at all, as it passes the `NODE_ARGS=...` string as a first argument and Node interprets it as a script filename. The result (of running `make dev-server` in `wp-desktop`) is the error I mentioned above:
```
Error: Cannot find module '/Users/jsnajdr/src/wp-desktop/calypso/NODE_ARGS=--max_old_space_size=8192'
```

**Comment by sgomes** [comment]
> **Validate fallback build in a separate `post*` script**
> Makes lines in `package.json` shorter 🙂 Cc @sgomes

Splitting that out into its own script sounds good to me! It should help contain changes too, as I believe newer `eslint` versions will require more parameters to avoid errors.

> **Update path to stats.json file in `whybundled` script**
> The (rarely used) `npm run whybundled` didn't have a correct path to `stats.json` (inside `client/` since the monorepo-ization)

That's actually one of my favourite and most often used tools in bringing down bundle sizes, so thank you for fixing that! 🙂

File: package.json [hunk 1]
```diff
@@ -44,7 +44,6 @@
 	"scripts": {
 		"preanalyze-bundles": "cross-env-shell CALYPSO_ENV=production EMIT_STATS=true PROGRESS=1 NODE_ARGS=--max_old_space_size=8192 npm run -s build-client-evergreen",
 		"analyze-bundles": "webpack-bundle-analyzer stats.json public/evergreen -h 127.0.0.1 -p 9898 -s gzip",
```
Comment (sgomes) [inline package.json]: Won't this line need the same fix as line 115?

File: package.json [hunk 2]
```diff
@@ -56,18 +55,19 @@
...
-		"build-client-evergreen": "cross-env-shell BROWSERSLIST_ENV=evergreen NODE_PATH=$NODE_PATH:server:client:. node $NODE_ARGS ./node_modules/webpack/bin/webpack.js --config client/webpack.config.js --display errors-only",
+		"build-client-fallback": "cross-env-shell BROWSERSLIST_ENV=defaults node $NODE_ARGS ./node_modules/webpack/bin/webpack.js --config client/webpack.config.js --display errors-only",
+		"postbuild-client-fallback": "npm run validate-fallback-es5",
+		"build-client-evergreen": "cross-env-shell BROWSERSLIST_ENV=evergreen node $NODE_ARGS ./node_modules/webpack/bin/webpack.js --config client/webpack.config.js --display errors-only",
 		"build-client-both": "CONCURRENT_BUILDS=2 concurrently -c cyan -n \"fallback ,evergreen\" \"npm run build-client-fallback\" \"npm run build-client-evergreen\"",
 		"build-client-if-prod": "node -e \"process.env.CALYPSO_ENV === 'production' && process.exit(1)\" || cross-env-shell NODE_ARGS=${NODE_ARGS:---max_old_space_size=8192} npm run build-client-both",
```
Comment (sgomes) [inline package.json]: I know this code was already here, but why do some scripts (like this one) extend `NODE_ARGS`, while others (like `preanalyze-bundles` and `prewhybundled`) rewrite it?

File: package.json [hunk 3]
```diff
@@ -56,18 +55,19 @@
...
 		"build-client-if-desktop": "node -e \"(process.env.CALYPSO_ENV === 'desktop' || process.env.CALYPSO_ENV === 'desktop-development') && process.exit(1)\" || cross-env-shell NODE_ARGS=${NODE_ARGS:---max_old_space_size=8192} npm run build-client-fallback",
 		"build-packages": "npx lerna run prepare --stream",
 		"build-packages:watch": "chokidar \"./packages/**\" -i \"./packages/*/dist/**\" -i \"**.css\" -i \"**.d.ts\" --debounce 1000 --throttle 10000 -c \"npm run build-packages\"",
-		"clean": "npm run -s clean:build && npm run -s clean:devdocs && npm run -s clean:public && npm run -s clean:packages",
-		"clean:build": "npx rimraf build server/bundler/*.json .babel-cache",
-		"clean:devdocs": "npx rimraf server/devdocs/search-index.js",
+		"clean": "run-s -s clean:*",
```
Comment (sgomes) [inline package.json]: Very nice 👍

Comment (blowery) [reply package.json]: `run-p` might be even faster for those of us with SSDs

**Comment by nsakaimbo** [comment]
@jsnajdr Thanks for handling my feedback in a constructive and positive way. I figured it would be better to err on the side of being transparent about any potential misunderstandings, and glad to hear we're on the same page. 😄 

I appreciate the breakdown of the underlying issue - I was definitely unaware this change inadvertently borked the `build/bundle.js` script 🤔(CI passed when this change was PR'd and I assumed all was good). Your changes here look good, and CI for wp-desktop [seems happy](https://circleci.com/gh/Automattic/wp-desktop/52184) with the fix. Does this mean we can also omit `NODE_PATH` from the desktop Makefile?

https://github.com/Automattic/wp-desktop/blob/124c942230f2f4c57e0497716718fdf14d8b6ae0/Makefile#L106

File: package.json (hunk 3 above)
Comment (jsnajdr) [reply package.json]: I considered `run-p`, too, but was afraid of race conditions like `npx rimraf` doing the download and install two times in parallel.

File: package.json (hunk 1 above)
Comment (jsnajdr) [reply package.json]: > Won't this line need the same fix as line 115?

Yes, I pushed a fix for `analyze-bundles`, too.

File: package.json (hunk 2 above)
Comment (jsnajdr) [reply package.json]: > why do some scripts extend `NODE_ARGS`, while others rewrite it?

That's a good point and I'm cleaning up `NODE_ARGS` in https://github.com/Automattic/wp-calypso/pull/38931/commits/42fb4f6fd40edb184a89e7ad090d805dd9b1e508 and further consolidating the build scripts in https://github.com/Automattic/wp-calypso/pull/38931/commits/1d9918436debe6fed1b4b062594a4b37e366c14d


After these changes, the scripts set and use the `NODE_ARGS` variable only at the place where `node` is actually spawned to run webpack or the server bundle -- `build-client-do` and `start-bundle-do`, respectively.

No other tasks set `max_old_space_size` now. The default value is OK for everyone, and there's also a way (used by `wp-desktop`) to override it by setting the `NODE_ARGS` environment variable.

The `build-client-do` consolidation works as follows: instead of two NPM tasks:
```
"build-client-fallback": "cross-env-shell BROWSERSLIST_ENV=fallback node bin/webpack [lot of webpack and node arguments]"
"build-client-evergreen": "cross-env-shell BROWSERSLIST_ENV=evergreen node bin/webpack [lot of webpack and node arguments]"
```
there are three and duplication is removed:
```
"build-client-do": "node bin/webpack [lot of webpack and node arguments]"
"build-client-fallback": "cross-env-shell BROWSERSLIST_ENV=fallback npm run build-client-do"
"build-client-evergreen": "cross-env-shell BROWSERSLIST_ENV=evergreen npm run build-client-do"
```

Comment (sgomes) [reply package.json]: That's a great solution, thank you! 👍

**Comment by jsnajdr** [comment]
> I was definitely unaware this change inadvertently borked the `build/bundle.js` script 🤔(CI passed when this change was PR'd and I assumed all was good)

@nsakaimbo As far as I know, the `start-build-fallback` script is ever run by `start-build-if-desktop` when running in the `desktop-development` mode. You'd need to run `make dev-server` in `wp-desktop/` to trigger this. The production builds and all the CI tasks run in different code paths.

> Does this mean we can also omit `NODE_PATH` from the desktop Makefile?

Yes, that should be possible with one caveat: you'll need to update externals definitions in the webpack config:

https://github.com/Automattic/wp-desktop/blob/develop/webpack.shared.js#L76-L78

so that they are mapped to paths relative to the current working directory when running the server bundle. See the changes that this PR does to the `client/webpack.config.node.js` file.

The `CALYPSO_SERVER=true` variable can also be removed from the desktop Makefile and be replaced with browserslist configuration. At this moment, I suspect that the server bundle for desktop (ran by the Node.js server inside Electron) is transpiled with the target being the default browserslist configuration, and that likely adds too many polyfills.

File: package.json (hunk 2 above)
Comment (jsnajdr) [reply package.json]: I'd like to try out the `NODE_OPTIONS` environment variable, too. It's supported directly by Node.js, and was added only in 8.x, which is not that ancient. We probably started setting `max_old_space_size` at a time when `NODE_OPTIONS` wasn't available yet.

**Review by sgomes — APPROVED** [review]
LGTM! Thank you for fixing these issues!

File: package.json [hunk 4]
```diff
@@ -42,9 +42,8 @@
 		"npm": "^6.12.1"
 	},
 	"scripts": {
-		"preanalyze-bundles": "cross-env-shell CALYPSO_ENV=production EMIT_STATS=true PROGRESS=1 NODE_ARGS=--max_old_space_size=8192 npm run -s build-client-evergreen",
-		"analyze-bundles": "webpack-bundle-analyzer stats.json public/evergreen -h 127.0.0.1 -p 9898 -s gzip",
-		"analyze-css": "node bin/analyze-css.js",
+		"preanalyze-bundles": "cross-env-shell CALYPSO_ENV=production EMIT_STATS=true PROGRESS=1 npm run -s build-client-evergreen",
```
Comment (blowery) [inline package.json]: maybe we can settle on either `1` or `true` as our truth marker?

File: package.json [hunk 5]
```diff
@@ -86,8 +87,9 @@
 		"start": "npm run -s build",
 		"poststart": "run-p -s start-build-if-web start-build-if-desktop build-packages:watch",
 		"reformat-files": "./node_modules/.bin/prettier --ignore-path .eslintignore --write \"**/*.{js,jsx,json,ts,tsx}\"",
-		"start-build-fallback": "cross-env-shell BROWSERSLIST_ENV=defaults NODE_PATH=$NODE_PATH:server:client:. node NODE_ARGS=${NODE_ARGS:---max_old_space_size=8192} build/bundle.js",
-		"start-build-evergreen": "cross-env-shell BROWSERSLIST_ENV=evergreen NODE_PATH=$NODE_PATH:server:client:. node $NODE_ARGS --max_old_space_size=8192 build/bundle.js",
+		"start-build-do": "cross-env-shell node ${NODE_ARGS:---max_old_space_size=8192} build/bundle.js",
```
Comment (blowery) [inline package.json]: i had no idea this syntax was possible `${NODE_ARGS:---max_old_space_size=8192}`

is that a cross-env-shell thing or a `npm scripts` thing?

File: package.json [hunk 6]
```diff
@@ -111,8 +113,8 @@
 		"typecheck": "tsc --noEmit",
 		"update-deps": "npx rimraf package-lock.json && npm run -s distclean && npm i && replace --silent 'http://' 'https://' . --recursive --include='package-lock.json' && touch -m node_modules",
 		"validate-fallback-es5": "npx eslint --parser-options=ecmaVersion:5 --no-eslintrc --no-ignore ./public/fallback/*.js",
-		"prewhybundled": "cross-env-shell CALYPSO_ENV=production EMIT_STATS=withreasons NODE_ARGS=--max_old_space_size=8192 npm run -s build-client",
-		"whybundled": "whybundled stats.json",
+		"prewhybundled": "cross-env-shell CALYPSO_ENV=production EMIT_STATS=withreasons npm run -s build-client-evergreen",
```
Comment (blowery) [inline package.json]: is there a way to skip this if we already have a `client/stats.json`?

**Review by blowery — APPROVED** [review]
couple little nits, but this is good progress! LGTM

File: package.json (hunk 4 above)
Comment (blowery) [reply package.json]: thanks!

File: package.json (hunk 5 above)
Comment (sgomes) [reply package.json]: I think it may be missing `NODE_ARGS=` beforehand, judging by the other lines.

Comment (jsnajdr) [reply package.json]: It's a bash syntax for fancy parameter expansion and setting default values. See the "Default Values" section in https://devhints.io/bash#parameter-expansions

`cross-env-shell` does some transforms to the bash-like command line that make it compatible with Windows cmd.exe. But it won't understand the `${FOO:-val}` syntax and this will be one of many things broken in Windows build.

File: package.json (hunk 6 above)
Comment (jsnajdr) [reply package.json]: Not easily, this is not `Makefile` 🤣

File: package.json (hunk 5 above)
Comment (jsnajdr) [reply package.json]: I removed `cross-env-shell` from this particular script, as it doesn't set any environment variables.

Comment (jsnajdr) [reply package.json]: > I think it may be missing `NODE_ARGS=` beforehand, judging by the other lines.

`NODE_ARGS=` is needed only if the caller wants to add some Node.js command line options, or override the default value of `max_old_space_size`. Currently, the only place that does this is the `wp-desktop` build.

File: package.json (hunk 6 above)
Comment (sirreal) [inline package.json]: I don't think we need to worry about x-platform support here, we can do something like the following:

```
[[ -f client/stats.json ]] && echo '`client/stats.json exists, skipping generation. To rebuild, remove the stats.json file.' || CALYPSO_ENV=production EMIT_STATS=withreasons npm run -s build-client-evergreen
```

Comment (sgomes) [reply package.json]: Do bear in mind that the stats file may already exist but not be the one we want, e.g. if `npm run analyze-bundles` was previously run. If we're going to do this, we should rename the file to `stats-with-reasons.json` to make it very clear this is the one we want.

Also, not sure how we should handle staleness. Presumably the developer will be able to tell that it took no time at all and thus it was an existing, possibly stale file?
