### PR TITLE
Limit Global Styles: Refactor the Color Dropdown in Newsletter Flow Implementation

### PR DESCRIPTION
**Pull request by rcrdortiz**
We're refactoring how the the color accent dropdown in the newsletter flow is implemented according to https://github.com/Automattic/dotcom-forge/issues/1226 and described in paYJgx-2B7-p2.

@SaxonF We didn't have anything designed for when we select an item in the dropdown. I went ahead and added a lock to the selected item. Feel free to suggest any changes to how it looks.

Captura de Pantalla 2022-11-18 a las 15 25 49

Adding the lock next to the arrow of the dropdown didn't look really good.

#### Proposed Changes

* Updated the select dropdown component so that we can have extra information for each item in the dropdown.
* Added a group label to separate between paid and free accent colors when needed.

#### Testing Instructions

* Open the Calypso live link
* Navigate to `/setup/newsletter/newsletterSetup`
* The dropdown should show a group label and lock icons as described in the main task.
* When you select an item with a lock, it should be clear that it's a locked item when the dropdown is collapsed.
* Navigate to `/setup/newsletter/newsletterSetup?flags=-limit-global-styles`
* It should work as expected (no locks should be shown)

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

### CODE REVIEW

File: client/components/select-dropdown/index.jsx [hunk 1]
```diff
@@ -218,6 +228,7 @@ class SelectDropdown extends Component {
 				>
 					<div id={ 'select-dropdown-' + this.instanceId } className="select-dropdown__header">
 						<span className="select-dropdown__header-text" aria-label={ this.props.ariaLabel }>
+							{ selectedExtra && <>{ selectedExtra }</> }
```
Comment (mmtr) [inline client/components/select-dropdown/index.jsx]: This seems redundant. `selectedExtra` shouldn't render anything when _falsy_, so I think this can be simplified?
```suggestion
							{ selectedExtra }
```

File: client/components/select-dropdown/item.jsx [hunk 2]
```diff
@@ -63,6 +64,7 @@ class SelectDropdownItem extends Component {
 							<Count count={ this.props.count } compact={ this.props.compactCount } />
 						</span>
 					) }
+					{ this.props.extra && <>{ this.props.extra }</> }
```
Comment (mmtr) [inline client/components/select-dropdown/item.jsx]: Same here:
```suggestion
					{ this.props.extra }
```

File: client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx [hunk 3]
```diff
@@ -32,40 +33,56 @@ enum COLORS {
...
+
+	return [
+		{
+			label: 'Lettre',
+			value: COLORS.Lettre,
+			icon: <ColorSwatch color={ COLORS.Lettre } />,
+		},
+		shouldLimitGlobalStyles && {
+			label: 'Unlock more colors with a Premium plan',
+			value: 'Unlock more colors with a Premium plan',
```
Comment (mmtr) [inline client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx]: This should be translatable.

File: client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx [hunk 4]
```diff
@@ -32,40 +33,56 @@ enum COLORS {
...
+			icon: <ColorSwatch color={ COLORS.VividPurple } />,
+			...locked,
+		},
+		{
+			label: 'Custom',
+			value: 'custom',
+			icon: <Icon className="custom_color_icon" icon={ color } width={ 22 } height={ 22 } />,
+			...locked,
+		},
+	].filter( ( item ) => !! item );
```
Comment (mmtr) [inline client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx]: Nitpick: I find this `filter` call confusing. You can avoid it entirely doing this:

```js
return [
	// ...
	... shouldLimitGlobalStyles ? [ {
		label: 'Unlock more colors with a Premium plan',
		value: 'Unlock more colors with a Premium plan',
		isLabel: true,
	} ] : [],
	// ...
];
```

**Review by mmtr — COMMENTED** [review]
Works great! Just left some minor feedback.

File: client/components/select-dropdown/index.jsx (hunk 1 above)
Comment (rcrdortiz) [reply client/components/select-dropdown/index.jsx]: Fixed

File: client/components/select-dropdown/item.jsx (hunk 2 above)
Comment (rcrdortiz) [reply client/components/select-dropdown/item.jsx]: Fixed

File: client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx (hunk 3 above)
Comment (rcrdortiz) [reply client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx]: Nice catch thanks! 
Fixed

File: client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx (hunk 4 above)
Comment (rcrdortiz) [reply client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx]: I knew it could be done somehow with destructuring, thanks!
Fixed

**Review by mmtr — APPROVED** [review]

**Comment by Copons** [comment]
Let's block this until we have confirmation from @SaxonF that the lock icon in the "selected state" looks nice from a designer's standpoint. 🙂

File: client/components/select-dropdown/item.jsx [hunk 5]
```diff
@@ -63,6 +64,7 @@ class SelectDropdownItem extends Component {
 							<Count count={ this.props.count } compact={ this.props.compactCount } />
 						</span>
 					) }
+					{ this.props.extra }
```
Comment (Copons) [inline client/components/select-dropdown/item.jsx]: What happens if an item has both `extra` and `count`?

File: client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx [hunk 6]
```diff
@@ -32,40 +33,60 @@ enum COLORS {
...
-	},
-	{
-		label: 'Custom',
-		value: 'custom',
-		icon: <Icon className="custom_color_icon" icon={ color } width={ 22 } height={ 22 } />,
-	},
-];
+const getColorOptions = ( shouldLimitGlobalStyles: boolean, groupLabelText: string ) => {
+	const locked = shouldLimitGlobalStyles && {
+		extra: <Gridicon icon="lock" size={ 18 } className="extra-gridicon" />,
```
Comment (Copons) [inline client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx]: Let's use the `lock` icon from `@wordpress/icons`

E.g.
`<Icon icon={ lock } width={ 22 } height={ 22 } />`
(width and height copied from the other `Icon` in this component, so they might not be perfect for the lock)

File: client/components/select-dropdown/item.jsx [hunk 7]
```diff
@@ -15,6 +15,7 @@ class SelectDropdownItem extends Component {
 		disabled: PropTypes.bool,
 		icon: PropTypes.element,
 		ariaLabel: PropTypes.string,
+		extra: PropTypes.element,
```
Comment (Copons) [inline client/components/select-dropdown/item.jsx]: I wonder.

Since this is fundamentally an icon, should we call this prop something like `secondaryIcon` and embrace the fact that... it's an icon! 😄

File: client/components/select-dropdown/style.scss [hunk 8]
```diff
@@ -244,6 +248,13 @@ $compact-header-height: 35;
 		}
 	}
 
+	.extra-gridicon {
+		fill: var(--color-neutral);
+		position: absolute;
+		top: #{( $option-height - 18 ) * 0.5}px;
+		right: #{$side-margin - 8 }px;
+	}
+
```
Comment (Copons) [inline client/components/select-dropdown/style.scss:253]: At a quick glance, these seem like they could be moved to the consumer (Stepper's `AccentColorControl`). 🤔 

What if the consumer doesn't use Gridicon but another type of icon (Gutenberg, Material, etc.)?

There are two magic numbers that feel a bit funky:
- `#{( $option-height - 18 ) * 0.5}px`
- `#{$side-margin - 8 }px;` (also beware of bracket spaces!)

Would they work appropriately with different icons?

File: client/components/select-dropdown/item.jsx (hunk 7 above)
Comment (rcrdortiz) [reply client/components/select-dropdown/item.jsx]: My idea was to not have this limited to an icon, since the dropdown is a shared component I didn't want to tie it to a specific naming.

File: client/components/select-dropdown/style.scss (hunk 8 above)
Comment (rcrdortiz) [reply client/components/select-dropdown/style.scss:253]: > There are two magic numbers that feel a bit funky
The first magic number is copied from this file. It's the magic number used to position the count.
Then in this same file, the icon is also positioned using a magic multiplier.

> Would they work appropriately with different icons?
The same could be asked about the current icon being shown by the element. If a consumer has specific needs he can always override the CSS rules if/when needed.

> At a quick glance, these seem like they could be moved to the consumer (Stepper's AccentColorControl). 🤔
I like the idea of providing a default positioning, just as this component does for the icon and count.

File: client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx (hunk 6 above)
Comment (rcrdortiz) [reply client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx]: Why should we use the `Icon` component instead of the `GridIcon` component? I've looked at the Calypso docs and they [only reference the `Gridicon` component when working with icons](https://wpcalypso.wordpress.com/devdocs/docs/icons.md).

I don't mind changing the icon, I just want to understand what is the deciding factor when working with icons, the official Calypso docs, or something else. If it is something else, could you point me to the docs?

**Comment by SaxonF** [comment]
Wondering if we even need the icon? 🤔  Looks good though. We can always iterate on this post launch.

File: client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx (hunk 6 above)
Comment (Copons) [reply client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx]: Mmh, I don't think there's a specific doc about it, but we've been internally talking about preferring WordPress Icons over other ones whenever possible.
An example: PuPv3-aHW-p2

In this case, we have an exact match, and the `@wordpress/icons` is already imported into the file, so it should be pretty _straightforward_! 🙂

File: client/components/select-dropdown/item.jsx (hunk 7 above)
Comment (rcrdortiz) [reply client/components/select-dropdown/item.jsx]: Changed the naming since I was changing some other things.

File: client/components/select-dropdown/style.scss (hunk 8 above)
Comment (rcrdortiz) [reply client/components/select-dropdown/style.scss:253]: In the end I moved the styles.

File: client/components/select-dropdown/item.jsx (hunk 5 above)
Comment (rcrdortiz) [reply client/components/select-dropdown/item.jsx]: In cases where we have both, only the count would be shown.

File: client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx (hunk 6 above)
Comment (rcrdortiz) [reply client/landing/stepper/declarative-flow/internals/steps-repository/components/accent-color-control/index.tsx]: Hmmm, I'm having some trouble with this. If I use `Icon` lock I'm getting some console errors.

`Uncaught TypeError: window.AppBoot is not a function`

If I try other icons it works fine 🤔

**Comment by Copons** [comment]
I've rebased this PR as it had major conflicts with #70160.
The new approach for the accent color dropdown required some deeper refactor, but I think I've restored the behavior intended by Richard.

---

@edanzer 👋 
Could you please check if the post-setup is still working as expected?
I've tried following the #70160 steps but for some reason they don't work for me in prod as well, so I might be missing something. 🤔 

For additional context, the changes introduced by this PR are only available in development environments, and are just visual (they don't/shouldn't affect any save logic). Pretty much they just add a "lock" icon to all options except the default one.

File: client/components/select-dropdown/index.jsx [hunk 9]
```diff
@@ -132,6 +134,17 @@ class SelectDropdown extends Component {
...
 
+	getSelectedSecondaryIcon() {
+		const { options, selectedSecondaryIcon } = this.props;
+		const { selected } = this.state;
+
+		if ( selectedSecondaryIcon ) {
+			return selectedSecondaryIcon;
+		}
+
+		return get( find( options, { value: selected } ), 'secondaryIcon' );
```
Comment (dsas) [inline client/components/select-dropdown/index.jsx:145]: We're slowly trying to remove lodash, non-blocking comment but this should probably be something like 
```suggestion
		return options.find(option => option.value === 'selected')?.secondaryIcon;
```

**Review by dsas — APPROVED** [review]

**Review by BogdanUngureanu — APPROVED** [review]
Works great! 🎉 Besides the lodash function Dean mentioned, LGTM!

File: client/components/select-dropdown/index.jsx (hunk 9 above)
Comment (Copons) [reply client/components/select-dropdown/index.jsx:145]: Makes sense, but I can't readily test that as it relies on the `options` array, which is not currently used in this case.

The Lodash implementation is the same as the other props, so it's not a big deal to keep it here, since we are not adding new Lodash imports. 🙂

**Comment by edanzer** [comment]
> @edanzer 👋
> Could you please check if the post-setup is still working as expected?
> I've tried following the #70160 steps but for some reason they don't work for me in prod as well, so I might be missing something. 🤔

@Copons (and others) - I just tested this and it seems to be working well for me. The main concern related my earlier PR (#70160) is that once you get to Launchpad, you can still edit the color as expected. 

What I did: From Launchpad, I clicked 'Personalize Newsletter' which loads the form with the same color control. I confirmed whatever color I had previously selected actually shows as selected. I updated the color again, saved, continued back to back to Launchpad, and confirmed my new color selection has been applied to the web preview on the Launchpad screen. I did several rounds of this and it all works as expected. I also tested that selecting a Custom color works.

**Comment by Copons** [comment]
@edanzer I'm incredibly relieved that everything was working fine in your tests, as I completely forgot that I asked your review earlier and had already deployed a few minutes ago 😅

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7650400

Thank you @rcrdortiz for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7650400).
