### PR TITLE
Use LanguagePicker in Calypso

### PR DESCRIPTION
**Pull request by sarayourfriend**
#### Changes proposed in this Pull Request

* Use the newly extracted LanguagePicker from #46020 in the Calypso language picker modal

#### Testing instructions

* Verify that `/new?flags=gutenboarding/language-picker` (click the language picker in the upper right-hand corner), `/me/account` and `/settings/general/:site`'s language pickers match the spec from @olaolusoga and @ollierozdarz here: p9oQ9f-kT-p2
* Verify that search works as expected (it should filter exactly the same as the previous search implementation)
* Verify that selecting a new language and saving works
* Verify that selecting a new language and dismissing the modal without apply changes does not save the new language selection

### CODE REVIEW

File: packages/language-picker/src/language-picker.tsx [hunk 1]
```diff
@@ -0,0 +1,150 @@
...
+		? getSearchedLanguages( languages, search, localizedLanguageNames )
+		: getFilteredLanguages();
+
+	return (
+		<>
+			<div className="language-picker__labels">
+				{ shouldDisplayRegions ? (
+					<>
+						<div className="language-picker__regions-label">{ __( 'regions' ) }</div>
+						<div className="language-picker__languages-label">{ __( 'language' ) }</div>
```
Comment (a8ci18n) [inline packages/language-picker/src/language-picker.tsx:122]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **17** times:
`translate( 'Language', { context: 'logged-out-homepage'} )` *ES Score: 8*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/use-lp-in-calypso)

File: packages/language-picker/src/language-picker.tsx [hunk 2]
```diff
@@ -0,0 +1,150 @@
...
+					</>
+				) : (
+					<div className="language-picker__search-results-label">{ __( 'search result' ) }</div>
```
Comment (a8ci18n) [inline packages/language-picker/src/language-picker.tsx:125]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **67** times:
`translate( 'Search results' )` *ES Score: 6*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/use-lp-in-calypso)

File: packages/language-picker/src/language-picker.tsx [hunk 3]
```diff
@@ -0,0 +1,186 @@
...
+						fitsContainer
+						placeholder={ __( 'Search languages…' ) }
+					/>
+				</div>
+			</div>
+			<div className="language-picker-component__labels">
+				{ shouldDisplayRegions ? (
+					<>
+						<div className="language-picker-component__regions-label">{ __( 'regions' ) }</div>
+						<div className="language-picker-component__languages-label">{ __( 'language' ) }</div>
```
Comment (a8ci18n) [inline packages/language-picker/src/language-picker.tsx:154]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **17** times:
`translate( 'Language', { context: 'logged-out-homepage'} )` *ES Score: 8*
See 2 additional suggestions in the [PR translation status page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/use-lp-in-calypso)

File: packages/language-picker/src/language-picker.tsx [hunk 4]
```diff
@@ -77,27 +113,96 @@ const LanguagePicker = ( { onSelectLanguage, languages, languageGroups }: Props
...
+							)
+						}
+					/>
 				</div>
+			</FlexBlock>
+			<FlexBlock className="language-picker-component__labels">
+				{ shouldDisplayRegions ? (
+					<>
+						<div className="language-picker-component__regions-label">{ __( 'regions' ) }</div>
+						<div className="language-picker-component__languages-label">{ __( 'languages' ) }</div>
```
Comment (a8ci18n) [inline packages/language-picker/src/language-picker.tsx:188]: :information_source: String reuse speeds up translation and improves consistency. The following string might make a good alternative and has already been translated **48** times:
`translate( 'Languages', { context: 'Help topic'} )` *ES Score: 10*

File: client/components/language-picker/modal.tsx [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+	onClose: () => void;
+	/**
+	 * Fires when the modal is dismissed with a language selection.
+	 */
+	onSelectLanguage: ( l: Language ) => void;
+	selectedLanguageSlug?: string;
+};
+
+const LanguagePickerModal = ( {
+	languages,
```
Comment (ramonjd) [inline client/components/language-picker/modal.tsx:33]: Hi! 

Was there any reason not to fetch the localized languages from the `/i18n/language-names` endpoint (to enable localized searching)? 

Granted, there is a bit of [data mashing](https://github.com/Automattic/wp-calypso/blob/58b9a18753a486af0e13192e58d740dae1922c51/client/components/language-picker/modal.jsx#L153) to get the filtered results, but we're removing a feature so I just wanted to make sure it's intentional.

We're using a query component for that at the moment `<QueryLanguageNames />` in the [deleted modal picker file](https://github.com/Automattic/wp-calypso/pull/46328/files#diff-85febdb2d08b1d64ca197b57b3012332ac71b2a8d72d91f43be2257e136f7479L593).

Also asked here p9oQ9f-kT-p2#comment-548

Thanks!

cc @Automattic/i18n

File: client/components/language-picker/modal.tsx [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+			} }
+		>
+			{ __( 'Apply Changes' ) }
+		</Button>,
+	];
+
+	return (
+		<Dialog
+			isVisible
+			onClose={ onClose }
```
Comment (ramonjd) [inline client/components/language-picker/modal.tsx:64]: We're also removing an existing [tracking event](https://github.com/Automattic/wp-calypso/pull/46328/files#diff-85febdb2d08b1d64ca197b57b3012332ac71b2a8d72d91f43be2257e136f7479L418).

**Comment by ramonjd** [comment]
It's looking really nice! ❤️ 

I just have a few questions about dissimilarities in the current search functionality.

I'll leave the design 👀  to @Automattic/dotcom-create-design  

- Verify that search works as expected (it should filter exactly the same as the previous search implementation) ⚠️ I can no longer search for languages using my current locale (or in English) and we seem to longer be making a tracking call (`calypso_languagepicker_closed`).
- Verify that selecting a new language and saving works ✅ 
- Verify that selecting a new language and dismissing the modal without apply changes does not save the new language selection ✅ 

There are also a few missing translations, but I expect that they're new.

Screen Shot 2020-10-30 at 12 30 47 pm

File: client/components/language-picker/modal.tsx (hunk 6 above)
Comment (saramarcondes) [reply client/components/language-picker/modal.tsx:64]: A good catch, we'll have to reimplement it using the provided hooks.

**Comment by saramarcondes** [comment]
This PR is also missing the empathy mode checkbox as well as the percent translated information. This is missing from the designs so I'm not sure where to put it. I've pinged design here p9oQ9f-kT-p2#comment-552

File: client/components/language-picker/modal.tsx (hunk 5 above)
Comment (saramarcondes) [reply client/components/language-picker/modal.tsx:33]: @ramonjd Do you have any pointers on how to do this from within Gutenboarding? We just need to get the response and the LanguagePicker component can already handle the result. I can see how to retrieve it in Calypso just using the existing query component, but that doesn't seem like it will work in Gutenboarding. I'm not at all familiar with how the data stores and all that stuff works.

Comment (ramonjd) [reply client/components/language-picker/modal.tsx:42]: > they don't come back for the correct locale 

The endpoint doesn't check the user's default locale (assuming a user is logged in), but relies on the `_locale` query parameter.

https://public-api.wordpress.com/wpcom/v2/i18n/language-names?_locale=es

Otherwise the "localized" names will be in English.

So, I guess we'd have to pass the current locale to the selector (and indirectly to the [resolver](https://github.com/Automattic/wp-calypso/pull/46328/files#diff-f562d06e677604cc31cb94c3e9ca15a0e427645394d5bf86be5e1442e1245068R9)).

Normally, the locale will be stored in the URL fragment, e.g., `/new/es`, or `/new/language-modal/de`

I see that [getLocale](https://github.com/Automattic/wp-calypso/blob/5278b2e11d97c9937158c4890692c0b2d7258de3/client/landing/gutenboarding/components/locale-context/index.tsx#L163) exists to check the URL for the existence of a valid locale.

You can test with the Language picker enabled by adding the following flag: `/new/?flags=gutenboarding/language-picker`

Having said all this, one of our tasks for[ i18n Gutenboarding](https://github.com/Automattic/wp-calypso/issues/37665) was to enable the language picker, so if you get the data-store/i18n selector/resolver/apiFetch accepting a locale then we could look at passing the right one from Gutenboarding later if you run out of time.

> adding a new i18n store to data-stores

👍 That's what I was going to suggest - nice work. It's where most of the state-related stuff for Gutenboarding lives. I'll still ping @razvanpapadopol and @yansern, who know the Gutenboarding architecture back to front to make sure. :)

Comment (jsnajdr) [reply client/components/language-picker/modal.tsx:42]: The `_locale` query parameter should be added automatically to every REST request, based on what's currently in Redux `state.ui.language`. There is a [dedicated `wpcom` interceptor handler](https://github.com/Automattic/wp-calypso/blob/master/client/lib/wp/localization/index.js) for that. For the older WP.COM endpoints (as opposed to the newer WP REST ones), the parameter name is `locale`, without the `_`.

Gutenberg's `apiFetch` code has a [similar handler](https://github.com/WordPress/gutenberg/blob/master/packages/api-fetch/src/middlewares/user-locale.js) that, however, always adds `_locale=user`, telling the server to use the logged-in user's locale rather than default `en`. In logged-out mode, however, this does nothing.

 The Core REST code seems to not support anything other than `user`: https://github.com/WordPress/WordPress/blob/master/wp-includes/l10n.php#L143-L145 But an endpoint like `i18n/language-names` can check the `_locale` param on its own.

> Normally, the locale will be stored in the URL fragment, e.g., `/new/es`, or `/new/language-modal/de`

In most cases, the locale is determined from the current logged in user. But the locale from URL should make its way to the Redux and `i18n-calypso`, too. The Signup and Login handlers that use these locale suffixes should have code for that.

Hopefully the above will be helpful when debugging the `_locale` param. Calypso code should always add it, and Gutenberg code will probably need to add it explicitly.

File: packages/language-picker/src/language-picker.tsx [hunk 7]
```diff
@@ -77,27 +113,96 @@ const LanguagePicker = ( { onSelectLanguage, languages, languageGroups }: Props
...
-				{ __( 'regions', __i18n_text_domain__ ) }
-			</div>
-			<div className="language-picker-component__content">
-				<div className="language-picker-component__category-filters">
-					{ renderCategoryButtons() }
+		<Flex className="language-picker-component" align="left">
+			<FlexBlock className="language-picker-component__heading">
+				<Flex justify="space-between" align="left">
+					<FlexItem className="language-picker-component__title wp-brand-font">
+						{ headingTitle || __( 'Select a language', __i18n_text_domain__ ) }
```
Comment (tyxla) [inline packages/language-picker/src/language-picker.tsx:140]: In some instances we use a textdomain, and in some we don't. What is the rationale behind that?

File: packages/language-picker/src/language-picker.tsx [hunk 8]
```diff
@@ -77,27 +113,96 @@ const LanguagePicker = ( { onSelectLanguage, languages, languageGroups }: Props
...
+			<FlexBlock className="language-picker-component__search">
+				<CustomSelectControl
+					label={ __( 'regions' ) }
+					hideLabelFromVision
+					value={ selectControlOptions.find( ( option ) => option.key === filter ) }
+					options={ selectControlOptions }
+					onChange={ ( { selectedItem } ) => selectedItem && setFilter( selectedItem.key ) }
+				/>
+				<div className="language-picker-component__search-mobile">
+					<Search
```
Comment (tyxla) [inline packages/language-picker/src/language-picker.tsx:158]: There is an odd popping when opening the search on mobile; you can see that the "Select a Language" title moves for a little before returning to its place.  I haven't investigated what it is, but it seems like the search bar gets too wide for a second when opening.

**Review by tyxla — COMMENTED** [review]
Thanks for getting this running, it's exciting to see it working!

I'd say this is great work overall! I've left some comments and questions for things I've found while testing. 

Furthermore, I'd love it if on top of @Automattic/ganon, @Automattic/i18n could also take a look. I remember @yuliyan has been spending some time with the language picker.

File: client/components/language-picker/index.jsx [hunk 9]
```diff
@@ -147,11 +156,10 @@ export class LanguagePicker extends PureComponent {
 
 		return (
 			<LanguagePickerModal
-				isVisible
 				languages={ languages }
 				onClose={ this.handleClose }
-				onSelected={ this.selectLanguage }
```
[the remark this answers is not in the document]
Comment (saramarcondes) [reply client/components/language-picker/index.jsx:153]: We'll want to re-incorporate those two checkboxes, I've pinged design (link above) to get information about how to handle those things.

File: packages/language-picker/src/language-picker.tsx (hunk 7 above)
Comment (saramarcondes) [reply packages/language-picker/src/language-picker.tsx:140]: It should be being used for all instances. Places that aren't are a mistake I believe (except for `createLanguageGroups` where the passed in `__` will have a text domain configured I believe... perhaps that is incorrect?).

File: client/components/language-picker/index.jsx (hunk 9 above)
[the remark this answers is not in the document]
Comment (tyxla) [reply client/components/language-picker/index.jsx:153]: Sounds good, looking forward to what comes out from that conversation.

File: packages/language-picker/src/language-picker.tsx (hunk 7 above)
Comment (tyxla) [reply packages/language-picker/src/language-picker.tsx:140]: > It should be being used for all instances. 
Gotcha. That's aligned to pbAok1-1Ao-p2 so we should be good.

> `createLanguageGroups` where the passed in `__` will have a text domain configured I believe

I think that's not the case, it doesn't have the textdomain configured, but it doesn't need to have a textdomain, because where we pass `__` is used only in Calypso context, where we don't need to specify a textdomain. If the package is used externally, then we can just pass a bound `__()` that specifies a textdomain, which isn't ideal, but will do the job.

Comment (saramarcondes) [reply packages/language-picker/src/language-picker.tsx:140]: Hmmm... In that case, we might as well pass `__i18n_text_domain__` in `createLanguageGroups` right? The signature should allow us to regardless and it doesn't cost anything right? Or is that incorrect?

File: packages/language-picker/src/language-picker.tsx (hunk 8 above)
Comment (saramarcondes) [reply packages/language-picker/src/language-picker.tsx:158]: @tyxla Do you mind recording your screen with this happening? I can't reproduce it at the moment.

File: packages/language-picker/src/language-picker.tsx [hunk 10]
```diff
@@ -77,27 +113,96 @@ const LanguagePicker = ( { onSelectLanguage, languages, languageGroups }: Props
...
+						placeholder={ __( 'Search languages…' ) }
+						onSearchClose={ () =>
+							setFilter(
+								findBestDefaultLanguageGroupId( selectedLanguage, languageGroups, filter )
+							)
+						}
+					/>
+				</div>
+				<div className="language-picker-component__search-desktop">
+					<Search
```
[the remark this answers is not in the document]
Comment (saramarcondes) [reply packages/language-picker/src/language-picker.tsx:171]: Oh good catch, I forgot to `stopPropagation` on the form event.

File: packages/language-picker/src/language-picker.tsx (hunk 7 above)
Comment (tyxla) [reply packages/language-picker/src/language-picker.tsx:140]: > we might as well pass `__i18n_text_domain__` in createLanguageGroups

I'm assuming yes, but I'm not 100% sure what you mean, could you please demonstrate it with an example?

File: packages/language-picker/src/language-picker.tsx (hunk 8 above)
Comment (tyxla) [reply packages/language-picker/src/language-picker.tsx:158]: Would love to do that, but for some reason I'm getting an error when trying to build with the latest branch:

```
@automattic/data-stores: src/auth/actions.ts(4,24): error TS7016: Could not find a declaration file for module '@wordpress/data-controls'
```

Are you able to reproduce that?

Comment (saramarcondes) [reply packages/language-picker/src/language-picker.tsx:158]: It looks like the CI is failing on this as well.

**Comment by saramarcondes** [comment]
@scinos Do you mind taking a look at the test failure? I believe it may have something to do with recent changes to module resolution in tests. The module works fine when running the app but fails to resolve the language picker when running tests.

**Comment by scinos** [comment]
I think the unit test are failing because the changes in #47002 .

After that change we don't produce `dist/cjs` by default anymore so `pkg.main` points to a missing file. And because Jest resolver only uses `pkg.main` or `pkg["calypso:src"]`, it is not able to resolve the package.

A potential solution would be to change `./test/module-resolver.js` to use `pkg.module` when the module comes from `packages/*`

/cc @saramarcondes @jsnajdr

**Comment by jsnajdr** [comment]
Yes, the unit tests are failing because the Jest resolver wants to use the `dist/cjs` files 🙁 I tried to fix this with returning the `module` value in the `module-resolver`, as @scinos suggests, but then something else broke: files in `node_modules` are not transformed by Babel, and then Jest/Node don't understand the import/export syntax. Trying to fix `transformIgnorePatterns` didn't work for some reason.

Debugging `@jest/transform` by inserting `console.log` statements also failed me, because the package is duplicated several times in the `node_modules` tree and I was unable to find the right one to patch 🤦 

As this is a too deep rabbit hole that I'm not willing to descend into right now, I simply partially reverted #47002 in d62a0fc and enabled `build:cjs` in the `prepare` tasks.

We should try to remove the `build:cjs` step again, this time making sure Jest is happy. But let's just unblock this PR quickly for now.

**Comment by scinos** [comment]
@jsnajdr I didn't know you were working on it. I try to fix it by changing the resolver (and limiting it to only packages from `./packages`) and seems to be working: #47180

**Comment by jsnajdr** [comment]
> I tried to fix it by changing the resolver (and limiting it to only packages from ./packages) and seems to be working

Nice! Does it really work also with this branch, where usages or `@automattic/search` and `@automattic/language-picker` are introduced to Calypso app? I'll try to test it later today.

**Comment by jsnajdr** [comment]
> I didn't know you were working on it.

I wanted to do a quick fix but didn't get anywhere 🙁 One of the things that tripped me was that when the resolver code throws an exception, that exception is swallowed without reporting and the resolution fails.

> seems to be working: #47180

Yes, I can confirm that it works for me, too. Once the PR is merged and this one is rebased on top, my changes from d62a0fc can be reverted.

**Comment by saramarcondes** [comment]
@ollierozdarz Hi there! Do you mind giving this PR a spin for a design review? It can be accessed here: https://calypso.live/?branch=add/use-lp-in-calypso

Please follow the instructions in the PR description for how to access the relevant areas 🙂

File: packages/language-picker/src/language-picker.tsx (hunk 8 above)
Comment (saramarcondes) [reply packages/language-picker/src/language-picker.tsx:158]: This should be fixed now that search is only 240px wide on desktop. Let me know if you can still reproduce it @tyxla, thanks! 🚀

File: yarn.lock [hunk 11]
```diff
@@ -19321,6 +19278,11 @@ lodash@*, lodash@^4.0.0, lodash@^4.1.1, lodash@^4.13.1, lodash@^4.15.0, lodash@^
   resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.15.tgz#b447f6670a0455bbfeedd11392eff330ea097548"
   integrity sha512-8xOcRHvCjnocdS5cpwXQXVzmmh5e5+saE2QGoeQmbKmRS6J3VQppPOIt0MnmE+4xlZoumy0GPG0D0MVIQbNA1A==
 
+lodash@4.17.20, lodash@^4.16.4, lodash@^4.17.20:
```
Comment (scinos) [inline yarn.lock:19281]: Looks like we can dedupe this one with the previous lodash?

**Review by yuliyan — COMMENTED** [review]
It looks very nice and seems to be working well!

I noticed one small glitch with the layout shifting during the search expansion transition. Tested in Chrome:
CleanShot 2020-11-18 at 16 47 36
_(Transitions at 10% speed, it's less noticeable at 1x)_

**Comment by saramarcondes** [comment]
@yuliyan Thank you for the bug report! I can't reproduce it in Firefox but indeed see it happening in Chrome. Good catch! I wonder if this is what @tyxla was talking about happening?

**Comment by saramarcondes** [comment]
@yuliyan Fix is up! Thanks again!

**Comment by yuliyan** [comment]
> @yuliyan Thank you for the bug report! I can't reproduce it in Firefox but indeed see it happening in Chrome.

@saramarcondes, I tested in Firefox, and it seems like it has the same bug but it's less noticeable. From what I see, the container that holds the search bar overflows horizontally in both browsers, but the difference between Chrome and Firefox is that, Firefox keeps the scroll position of the container to the left and Chrome scrolls right to keep the overflown elements in view.

**Comment by ollierozdarz** [comment]
Hi @saramarcondes, I think this meets the functionally we have been chatting about. Good job. If it's not too late, I'd probably suggest putting a Grey border around the search input in it's unselected state for the desktop view, as I worry it's easy to miss. 

**Example:**
Screen Shot 2020-11-19 at 10 12 52 am

**Review by tyxla — COMMENTED** [review]
Thanks for your continuous great work on this one, @saramarcondes!

One thing that I noticed was that on mobile (480px), things looked misaligned a little bit:



Perhaps that impression is caused by several facts:
* The search button is a bit too wide, and it's not aligned to the right. 
* The cancel button is not left aligned with anything because of the inner button padding
* Title seems to be more indented than the select box and the list below.

That's just my personal opinion, though, and it might be best to consult with a designer on this one.

Also, I've started reviewing the entirety of this PR today, but I'm afraid it's grown beyond the point where it should be a single PR already. Reviewing such high-impact PRs can be really difficult, and I personally can't be confident that I'm not missing a bunch of stuff when reviewing and testing it. Have you considered splitting it into multiple PRs? One way we could split it to multiple PRs could be:

* Introducing i18n functionality to the data-stores package
* Changes to the language-picker package
* Changes to the search package
* Updating language picker in Gutenboading
* Updating language picker in Calypso language picker component

Sorry for proposing this so late, but I'm starting to feel that I can miss something while reviewing, and I'm not reviewing it thoroughly and with the usual quality. 

What do you think @saramarcondes?

File: packages/language-picker/src/language-picker.tsx (hunk 8 above)
Comment (tyxla) [reply packages/language-picker/src/language-picker.tsx:158]: Can't reproduce anymore, I think it's working well now. The only nit I have here is that while the search is opening, there's a scroll appearing. It disappears once the search box ends in its place. Is this something we can easily prevent?

**Comment by yuliyan** [comment]
I agree with @tyxla that splitting the PR could improve the review process. For me personally, there are changes in some packages and areas of the code that I'm unfamiliar with, and if those were separated it would've been easier to only get involved in PRs where I can provide more valuable input.

However, given that the PR is already in late stage, I'm not sure how much effort would it take to split it and if would be worth it. I don't want to influence your decision in any way, just sharing my thoughts.

**Comment by saramarcondes** [comment]
@yuliyan and @tyxla re: splitting the PR.

I agree with both of y'all. I'm a little wary as it will extend an already long process but that should be okay, there's no real rush for this work.
