### PR TITLE
Update Babel to support new typescript syntax

### PR DESCRIPTION
**Pull request by sgomes**
This PR updates Babel to support the new `import type` and `export type` typescript syntax. All Babel packages (and some dependencies) were updated to ensure consistency between them.

#### Changes proposed in this Pull Request

* Update Babel versions to support the new `import type` and `export type` typescript syntax

#### Testing instructions

Ensure that the builds continue to work normally, by checking if the live branch gets built normally and the E2E tests don't fail.

### CODE REVIEW

**Comment by sgomes** [comment]
Note: the size increases aren't as bad as the matticbot comments above makes it appear. The second graph on this page illustrates things more clearly: http://iscalypsofastyet.com/branch?branch=update/babel-to-core-7.9.0

Overall we see a 22KB (compressed) increase across the sum of all chunk sizes, which is quite reasonable, considering most users will only load a small portion of these as they navigate through the application.

**Comment by sgomes** [comment]
Rebased on master and auto-merged. Checking whether that was successful.

**Comment by sgomes** [comment]
PR rewritten, should be ready for review again.

**Comment by sgomes** [comment]
This appears to be adding 153KB to gutenboarding now, for some reason. Investigating.

**Comment by sirreal** [comment]
> This appears to be adding 153KB to gutenboarding now, for some reason. Investigating.

That could easily a `@babel/runtime` mismatch with `@wordpress/*` packages.

The packages we _just_ updated to (https://github.com/Automattic/wp-calypso/pull/39644) appear to be using `@babel/runtime@^7.8.3`.

https://unpkg.com/browse/@wordpress/components@9.3.0/package.json

**Comment by sgomes** [comment]
> That could easily a `@babel/runtime` mismatch with `@wordpress/*` packages.
> 
> The packages we _just_ updated to (#39644) appear to be using `@babel/runtime@^7.8.3`.

`@babel/runtime@^7.8.3` should be compatible with the newly installed version, `7.9.0`, so I'm not sure that's the issue.

**Comment by sgomes** [comment]
The problem seems to have been introduced in #39644; there are now multiple versions of several `@wordpress/foo` packages, namely `@wordpress/api-fetch`, `@wordpress/compose`, `@wordpress/data-controls`, `@wordpress/element` and `@wordpress/url`. When deduplicating, in this PR, this causes the dependencies to be moved into Gutenboarding and thus its size to grow.

Dashicons has also grown significantly, by about 30KB, and this change appears to make Gutenboarding pick up the new version.

**Comment by sirreal** [comment]
This errors [`/new`](https://calypso.live/new?branch=update/babel-to-core-7.9.0) (formerly `/gutenboarding`).

**Review by sirreal — CHANGES_REQUESTED** [review]
This errors [`/new`](https://calypso.live/new?branch=update/babel-to-core-7.9.0) (formerly `/gutenboarding`).

```
An error occurred while running 'mapSelect': O is not a function
```

**Comment by sgomes** [comment]
Dropping this PR. Other fixes need to be applied before we can look at upgrading Babel.
