### PR TITLE
Framework: Initialize localStorage polyfill at start of boot

### LINKED ISSUE #6555: Calypso not loading in Safari private window
#### Steps to reproduce
1. In Safari on a computer, go to File > New Private Window, or in Safari on a mobile device, tap Private to open a new private window
2. Go to https://wordpress.com
#### What I expected

I expected Calypso to load as usual.
#### What happened instead

I ended up on a blank screen with the WordPress logo, and the console displayed these errors:

```
QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
TypeError: window.AppBoot is not a function. (In 'window.AppBoot()', 'window.AppBoot' is undefined)
```
#### Browser / OS version

Safari 9.1.1 (11601.6.17) / Mac OS X 10.11.5 (15F34)
Safari / iPhone 6 iOS 9.3.2 (13F69)
#### Screenshot / Video

screen shot 2016-07-06 at 3 34 25 pm
#### Context / Source
# user-report

113375-h

### PR DESCRIPTION
**Pull request by aduth**
Fixes #6555
Suspected regression in #6236 ([`lib/abtest`](https://github.com/Automattic/wp-calypso/blob/master/client/lib/abtest/index.js) pulls in `store`)

This pull request seeks to resolve an issue where Safari Private Mode does not load correctly because of an attempt to access `localStorage` (not available). Our [`localStorage` polyfill](https://github.com/Automattic/wp-calypso/tree/master/client/lib/local-storage) is targeted at resolving this case, but must be loaded before any dependencies making use of `store` or `localStorage`. This pull request moves the initialization to the top of the boot file to ensure that it is always executed first.

__Testing instructions:__

I was never able to reproduce the original issue in development mode locally, perhaps due to some configuration flag that's only active in production (makes sense if it is ABTest related). You may want to search internal documentation for running production mode locally to verify the fix (which I did to verify resolution), else ensure that no regressions occur in using the application. Specifically, ensure that you can load Calypso in Safari Private Mode.

/cc @rachelmcr, @bisko, @blowery, @mjuhasz

Test live: https://calypso.live/?branch=fix/6555-localstorage-private

### CODE REVIEW

**Comment by rachelmcr** [comment]
I confirmed that Calypso loads for me in Safari Private Mode on the calypso.live branch.

**Comment by aduth** [comment]
@rachelmcr : Do you see it being broken at https://calypso.live/?branch=master ?

**Comment by bisko** [comment]
Confirmed broken on the `calypso.live` `master` branch.
Confirmed working on the `calypso.live` `fix/6555-localstorage-private` branch.

Unable to reproduce on local Calypso, because it seems that `localStorage` has a bit of weird behaviour on local sites.

**Comment by rachelmcr** [comment]
Hm, I checked the `master` branch on calypso.live and it's working for me there, so at least on my end I can't confirm the fix based on calypso.live testing.

**Comment by aduth** [comment]
Ref: 2834-gh-calypso-pre-oss
