### ISSUE TITLE
Jetpack: Disconnecting sites doesn't work

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-calypso#22794]
#### Steps to reproduce
1. Starting at URL: https://wordpress.com with a Jetpack site that no longer exists
2. Click "My Sites" and use the red icon and click "Remove Site"
3. Complete the survey
4. Click "Disconnect"

#### What I expected

Until recently, a confirmation dialog success message was shown saying site was disconnected

#### What happened instead

Nothing, site **isn't** disconnected

#### Browser / OS version

Chrome on macOS

#### Screenshot / Video

![disconnect site](https://user-images.githubusercontent.com/128826/36648768-412ba4ca-1ae3-11e8-9733-32ff382faa92.gif)

#### Context / Source
 #automated-testing

**Comment by rachelmcr** [comment]
I confirmed the issue and noticed the console error `Uncaught TypeError: u(...).then is not a function` when I hit the Disconnect button.

![screenshot 2018-02-26 10 11 53](https://user-images.githubusercontent.com/8658164/36664748-8f5f7e60-1add-11e8-9ec0-ff95fb69a8ca.png)

**Comment by seear** [comment]
Seems like this has been caused by #22362 and #22724.

@eliorivero the `mapDispatchToProps` args to `connect` are seem broken in both those components—watch the errors in dev mode. I'm working on a fix.
