### PR TITLE
Signup: Use Redux for handling/persisting signup progress

### PR DESCRIPTION
**Pull request by jsnmoon**
Part of step 2 for #6709; builds on #25645. See p9xfpQ-8z-p2 for further discussion.

This change reworks the SignupProgressStore to use Redux instead of Flux. The SignupProgressStore is responsible for tracking and persisting the user's progression through our various signup flows.

Previously, this store persisted the current user's signup progress into localStorage via the [store.js](https://www.npmjs.com/package/store). It now relies on Calypso's [Redux state persistence mechanism](https://github.com/Automattic/wp-calypso/blob/master/client/state/initial-state.js#L166) which relies on [localforage](https://www.npmjs.com/package/localforage).

Existing signup flow behavior should remain identical as before.

Some notes: 

1. The signup flow is designed to cross the logged-out/logged-in boundary. Since the store persisted in logged-out state isn't loaded in the logged-in state, I'm assuming that the progress store is only useful during the signup process to the logged-out user. Once a user completes signup by completing the `user` step, we discard the logged-out state.

2. Upon construction of the signup flow controller, we invoke a function to discard steps not associated with the current flow. This ensures that we clear out stale/invalid steps persisted by the progress state in the Redux store.

# Testing instructions
1. Spin up this branch either on the [live branch](https://calypso.live/?branch=reduxify/signup-progress-store-part-2) or locally.
2. Go through the entirety of a signup flow such as [`/start`](http://calypso.localhost:3000/start/domains). 
3. Verify that you are correctly redirected following the signup flow. Depending on your A/B test configuration, this is either your new site or the new user checklist page.

### CODE REVIEW

**Comment by alisterscott** [comment]
I'm looking at why the e2e tests are failing, it looks like upon completing sign up on this branch the customer is redirected straight into /wp-admin on the new site. Any reason for this?

**Comment by jsnmoon** [comment]
> I'm looking at why the e2e tests are failing, it looks like upon completing sign up on this branch the customer is redirected straight into /wp-admin on the new site. Any reason for this? (@alisterscott)

Hmm, it looks like the refactor unintentionally affected the redirection logic. I'll update when I have something more concrete to report.

**Comment by alisterscott** [comment]
I see a console error revisiting the start page after going through the flow:

```
build.382083f4ff53ca58eb95.opt.js:1 Error: Tried to read redux state before store was ready
    at Object.get (signup.7fdc90687b2b92753b37.opt.js:1)
```

Steps to Reproduce:

1. Visit https://calypso.live/start?branch=reduxify/signup-progress-store-part-2 in a new browser window (logged out)
2. Progress to step 4 account
3. Revisit https://calypso.live/start?branch=reduxify/signup-progress-store-part-2
4. Nav back through steps to start page (about)
5. Revisit https://calypso.live/start?branch=reduxify/signup-progress-store-part-2
6. Error comes up in console and screen won't load - see screen recording:

sign up

**Review by alisterscott — DISMISSED** [review]
I left a comment with an error that occurs when revisiting start

**Comment by alisterscott** [comment]
Re-tested session store bug and works well now 👍

**Review by alisterscott — APPROVED** [review]
Looks good from a product perspective.
All sign up e2e tests passing.
Couldn't find any issues in manual testing.
Tested IE11 sign ups also.
Thanks for this change.

**Comment by blowery** [comment]
@jsnmoon looks like some changes happened to signup around this PR. Could you take a look?

**Comment by jsnmoon** [comment]
> @jsnmoon this needs a minor rebase and then I think we can land it. Can you take a look? I nearly committed the rebase myself, but I'm not 100% sure it's as simple as it appears. (@blowery)

This has been rebased to account for changes introduced by #25690.

**Comment by alisterscott** [comment]
Hi @jsnmoon 

I retested this since rebasing and I can't see @taggon's fix in this branch any more.

**Steps**

1. As a non-logged-in customer visit https://calypso.live/start?branch=reduxify/signup-progress-store-part-2
2. Proceed to the account screen
3. Enter email of existing account
4. Use the log in now link
5. Customer is redirected back to the start of the sign up flow when it should keep their position

**Comment by jsnmoon** [comment]
> I retested this since rebasing and I can't see @taggon's fix in this branch anymore. (@alisterscott)

Unfortunately, we currently don't have a way to persist Redux state between the logged-out/logged-in boundary. This sadly means we would intentionally undo #25690 with this PR.

I currently don't have a straightforward fix for this; I started this reduxification effort assuming that we didn't have significant UX relying on passing data through the logged-in boundary. 

Sorry @taggon :(

**Comment by jsnmoon** [comment]
Unrelated pages are currently failing on `wp-e2e-tests-full` at the moment. Should be safe to disregard.

File: client/lib/signup/progress-store.js [hunk 1]
```diff
@@ -4,139 +4,85 @@
...
 const SignupProgressStore = {
-	get: function() {
-		return clone( signupProgress );
+	currentValue: null,
+	reduxStore: null,
+	subscribers: new Map(),
+
+	get() {
+		if ( ! this.reduxStore ) {
+			throw new Error( 'Tried to read redux state before store was ready' );
```
Comment (blowery) [inline client/lib/signup/progress-store.js]: maybe just return instead of throwing?

File: client/lib/signup/progress-store.js [hunk 2]
```diff
@@ -4,139 +4,85 @@
...
+		}
+		return cloneDeep( getSignupProgress( this.reduxStore.getState() ) );
```
Comment (blowery) [inline client/lib/signup/progress-store.js]: why the `cloneDeep`?

File: client/lib/signup/progress-store.js [hunk 3]
```diff
@@ -4,139 +4,85 @@
...
-	getFromCache: function() {
-		loadProgressFromCache();
-		return this.get();
+	set( input ) {
+		this.reduxStore.dispatch( {
+			type: SIGNUP_PROGRESS_SET,
+			steps: input,
+		} );
+	},
+	setReduxStore( reduxStore ) {
```
Comment (blowery) [inline client/lib/signup/progress-store.js]: I think you can use the `redux-bridge` instead of having to hold onto a ref to the redux store.

File: client/signup/main.jsx [hunk 4]
```diff
@@ -88,23 +92,21 @@ class Signup extends React.Component {
...
 			loginHandler: null,
 			hasCartItems: false,
 			plans: false,
 			previousFlowName: null,
-			resumedAfterLogin: false,
 		};
 	}
 
-	componentWillMount() {
+	UNSAFE_componentWillMount() {
```
Comment (blowery) [inline client/signup/main.jsx]: can we move this to DidMount or the constructor instead of moving to UNSAFE_*?

File: client/signup/main.jsx [hunk 5]
```diff
@@ -291,12 +286,11 @@ class Signup extends React.Component {
 	};
 
 	handleFlowComplete = ( dependencies, destination ) => {
-		debug( 'The flow is completed. Logging you in...' );
+		debug( `The flow is completed. Destination: ${ destination }` );
```
Comment (blowery) [inline client/signup/main.jsx]: super minor, but using a string placeholder avoids the string concat when debug is disabled. like
`debug( 'The flow is completed. Destination: %s', destination )`

File: client/lib/signup/progress-store.js (hunk 2 above)
Comment (blowery) [reply client/lib/signup/progress-store.js]: it was more curiosity than anything. I assume this code is going to get thrown out anyway when we remove the flux store, so ... probably fine to leave it. `cloneDeep` isn't cheap.

File: client/lib/signup/progress-store.js (hunk 3 above)
Comment (jsnmoon) [reply client/lib/signup/progress-store.js]: It seems like we'd want to continue using the `setReduxStore` pattern in the signup (for now) to preserve consistency with other signup stores. 

Also, it seems like value change subscription pattern is not yet supported in `redux-bridge`, so it might not be sufficient here without additional work (e.g. `SignupProgressStore.on( 'change', callbackFn );`). I might be wrong, though.

File: client/signup/main.jsx (hunk 4 above)
Comment (jsnmoon) [reply client/signup/main.jsx]: Given the large and interconnected nature of the main signup script, I wanted to avoid introducing more changes than necessary with this PR.

It's certainly worth considering once we land this change, though.

File: client/lib/signup/progress-store.js (hunk 2 above)
Comment (jsnmoon) [reply client/lib/signup/progress-store.js]: I just reviewed all instances of `ProgressStore.get()` and confirmed that we don't mutate the object anymore with this change. I'll go ahead and remove it.
